package jammnews.dialogs;

import jammnews.JAMMNewsUI;
import jammnews.tasks.Mix;
import java.util.LinkedList;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dhergaarden
 */

public class MixDialog extends javax.swing.JFrame {

    JAMMNewsUI parent;
    
    //for edit
    boolean edit = false;
    int index;
    
    private LinkedList<String> listInputs = new LinkedList<>();
    private LinkedList<Integer> listDly = new LinkedList<>();
    /**
     * Creates new form MixDialog
     */
    public MixDialog(JAMMNewsUI p) {
        this.parent = p;
        initComponents();
    }
    
    public MixDialog(JAMMNewsUI p, Mix m, int index) {
        this.parent = p;
        initComponents();
        
        for(int d : m.getDelays())
        {
            listDly.add(d);
        }
        
        for(String i : m.getInputs())
        {
            listInputs.add(i);
        }
        refreshList();
        
        outputField.setText(m.getOutput());
        durationCbox.setSelectedItem(m.getDuration());
        edit = true;
        this.index = index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        delBtn = new javax.swing.JButton();
        locField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        delayField = new javax.swing.JTextField();
        outputField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        durationCbox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        locList = new java.awt.List();
        delayList = new java.awt.List();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        delBtn.setText("Del");
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Locations");

        jLabel2.setText("Delays");

        jLabel3.setText("Location");

        jLabel4.setText("Delay ms");

        jLabel5.setText("Output");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        durationCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "first", "longest", "shortest" }));

        jLabel6.setText("Duration");

        locList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                locListItemStateChanged(evt);
            }
        });
        locList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locListActionPerformed(evt);
            }
        });

        delayList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                delayListItemStateChanged(evt);
            }
        });
        delayList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delayListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(saveBtn)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(delayField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(425, 425, 425)
                                    .addComponent(addBtn))
                                .addComponent(delBtn)
                                .addComponent(locList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(durationCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(delayList, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(durationCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(delBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(locList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delayList, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBtn))
        );

        durationCbox.setSelectedIndex(0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        listDly.remove(locList.getSelectedIndex());
        listInputs.remove(locList.getSelectedIndex());
        refreshList();
    }//GEN-LAST:event_delBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        
        try
        {
            Integer.parseInt(delayField.getText());
        }
        catch(Exception e) {
            System.out.println(e);
            delayField.setText("0");
        }
        
        if(locField.getText().length() > 0)
                
        {
            listDly.add(Integer.parseInt(delayField.getText()));
            listInputs.add(locField.getText());
            refreshList();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Fill all fields!");
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
        if(outputField.getText().length() > 0 && locList.getItemCount() > 1)
        {
            Mix m = new Mix();
            for (int dly : listDly) 
            {
                m.setDelays(dly);
            }
            
            for (String input : listInputs) 
            {
                m.setInputs(input);
            }
            
            
            m.setOutput(outputField.getText());
            m.setDuration(durationCbox.getSelectedItem().toString());
            
            if(edit)
            {
                parent.editTaskHandler(m, index);
                edit = false;
                clearFields();
                this.dispose();
            }
            else
            {
                parent.addTaskHandler(m);
                clearFields();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Fill all fields!");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void locListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locListActionPerformed

    }//GEN-LAST:event_locListActionPerformed

    private void delayListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delayListActionPerformed
        
    }//GEN-LAST:event_delayListActionPerformed

    private void locListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_locListItemStateChanged
        delayList.select(locList.getSelectedIndex());
    }//GEN-LAST:event_locListItemStateChanged

    private void delayListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_delayListItemStateChanged
        locList.select(delayList.getSelectedIndex());
    }//GEN-LAST:event_delayListItemStateChanged

    private void refreshList()
    {
        locList.removeAll();
        delayList.removeAll();
        
        for (int dly : listDly) 
        {
            delayList.add(dly + "");          
        }
        
        for (String input : listInputs) 
        {
            locList.add(input);
        }       
    }
    
    private void clearFields()
    {
        listDly.clear();
        listInputs.clear();
        refreshList();
        
        outputField.setText("");
        delayField.setText("");  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextField delayField;
    private java.awt.List delayList;
    private javax.swing.JComboBox<String> durationCbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField locField;
    private java.awt.List locList;
    private javax.swing.JTextField outputField;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
