/*
 * To change this license header, choose License Headers in Project Properties.
 * T    @Override
    public void setSelectedItem(Object anItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getSelectedItem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getElementAt(int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void addListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void removeListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    @Override
    public void setSelectedItem(Object anItem) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getSelectedItem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public int getSize() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public Object getElementAt(int index) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void addListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void removeListDataListener(ListDataListener l) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
o change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jammnews.dialogs;

import jammnews.tasks.Concat;
import jammnews.tasks.Download;
import jammnews.tasks.Mix;
import jammnews.tasks.Order;
import jammnews.tasks.ShellCmd;
import jammnews.tasks.SilenceReplace;
import javax.swing.ComboBoxModel;

/**
 *
 * @author dhergaarden
 */
public class TaskDialog extends javax.swing.JFrame {

    /**
     * Creates new form TaskDialog
     */
    jammnews.JAMMNewsUI parent;
    
    public TaskDialog(jammnews.JAMMNewsUI p) {
        initComponents();
        parent = p;
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HourCBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SecCBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        MinCBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        GeneralOutputField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        DownloadRBtn = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        UrlField = new javax.swing.JTextField();
        AuthChkBox = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        PassField = new javax.swing.JTextField();
        SrcFileRBtn = new javax.swing.JRadioButton();
        SrcFileField = new javax.swing.JTextField();
        monChkBox = new javax.swing.JCheckBox();
        TueChkBox = new javax.swing.JCheckBox();
        WedChkBox = new javax.swing.JCheckBox();
        ThuChkBox = new javax.swing.JCheckBox();
        FriChkBox = new javax.swing.JCheckBox();
        SatChkBox = new javax.swing.JCheckBox();
        SunChkBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        rptChkBox = new javax.swing.JCheckBox();
        saveBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        silenceBorderSlider = new javax.swing.JSlider();
        jLabel12 = new javax.swing.JLabel();
        slcBorderLbl = new javax.swing.JLabel();
        minSilenceLengthSlider = new javax.swing.JSlider();
        jLabel14 = new javax.swing.JLabel();
        silenceLengthLbl = new javax.swing.JLabel();
        EnableSilenceReplaceChkBox = new javax.swing.JCheckBox();
        skipFirstCBox = new javax.swing.JCheckBox();
        replacementAudioField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        enableBgAudio = new javax.swing.JCheckBox();
        bgAudioField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        EnableIntroChk = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        introField = new javax.swing.JTextField();
        cctIntroRBtn = new javax.swing.JRadioButton();
        StartNewsAtRBtn = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        startNewsMsSpin = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        enableOutroChkBox = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        OutroField = new javax.swing.JTextField();
        cctOutroRBtn = new javax.swing.JRadioButton();
        startOutroRBtn = new javax.swing.JRadioButton();
        startOutroMsBefore = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Time");

        HourCBox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for(int i = 0; i < 24; i++)
        HourCBox.addItem(i + "");
        HourCBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HourCBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Hour");

        jLabel3.setText("Min");

        SecCBox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for(int i = 0; i < 60; i++)
        SecCBox.addItem(i + "");

        jLabel4.setText("Sec");

        MinCBox.setModel(new javax.swing.DefaultComboBoxModel<>());
        for(int i = 0; i < 60; i++)
        MinCBox.addItem(i + "");

        jLabel5.setText("Output file");

        jLabel17.setText("Source");

        DownloadRBtn.setSelected(true);
        DownloadRBtn.setText("Download");
        DownloadRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownloadRBtnActionPerformed(evt);
            }
        });

        jLabel18.setText("URL");

        UrlField.setText("http://");
        UrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrlFieldActionPerformed(evt);
            }
        });

        AuthChkBox.setText("Authentication");
        AuthChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthChkBoxActionPerformed(evt);
            }
        });

        jLabel19.setText("Username");

        jLabel20.setText("Password");

        UserField.setEnabled(false);
        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });

        PassField.setEnabled(false);

        SrcFileRBtn.setText("Source file");
        SrcFileRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrcFileRBtnActionPerformed(evt);
            }
        });

        SrcFileField.setEnabled(false);
        SrcFileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SrcFileFieldActionPerformed(evt);
            }
        });

        monChkBox.setSelected(true);
        monChkBox.setText("M");

        TueChkBox.setSelected(true);
        TueChkBox.setText("T");

        WedChkBox.setSelected(true);
        WedChkBox.setText("W");
        WedChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WedChkBoxActionPerformed(evt);
            }
        });

        ThuChkBox.setSelected(true);
        ThuChkBox.setText("T");

        FriChkBox.setSelected(true);
        FriChkBox.setText("F");

        SatChkBox.setSelected(true);
        SatChkBox.setText("S");

        SunChkBox.setSelected(true);
        SunChkBox.setText("S");

        jLabel6.setText("Days");

        rptChkBox.setText("Repeat hourly");
        rptChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptChkBoxActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(UrlField, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HourCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MinCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SecCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(DownloadRBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AuthChkBox)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(GeneralOutputField, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(monChkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TueChkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WedChkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ThuChkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FriChkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SatChkBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SunChkBox))
                    .addComponent(SrcFileField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveBtn)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(rptChkBox)
                    .addComponent(SrcFileRBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rptChkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(HourCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(MinCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(SecCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monChkBox)
                    .addComponent(TueChkBox)
                    .addComponent(WedChkBox)
                    .addComponent(ThuChkBox)
                    .addComponent(FriChkBox)
                    .addComponent(SatChkBox)
                    .addComponent(SunChkBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GeneralOutputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(DownloadRBtn)
                    .addComponent(AuthChkBox)
                    .addComponent(UserField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(UrlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PassField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SrcFileRBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SrcFileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(saveBtn))))
        );

        jTabbedPane1.addTab("General", jPanel1);

        silenceBorderSlider.setValue(30);
        silenceBorderSlider.setEnabled(false);
        silenceBorderSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                silenceBorderSliderStateChanged(evt);
            }
        });

        jLabel12.setText("Silence border");

        slcBorderLbl.setText("-30");

        minSilenceLengthSlider.setMaximum(1000);
        minSilenceLengthSlider.setToolTipText("");
        minSilenceLengthSlider.setValue(100);
        minSilenceLengthSlider.setEnabled(false);
        minSilenceLengthSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minSilenceLengthSliderStateChanged(evt);
            }
        });

        jLabel14.setText("Minimum silence length");

        silenceLengthLbl.setText("1.00");

        EnableSilenceReplaceChkBox.setText("Enable silence replace");
        EnableSilenceReplaceChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnableSilenceReplaceChkBoxActionPerformed(evt);
            }
        });

        skipFirstCBox.setText("Skip first");
        skipFirstCBox.setEnabled(false);

        replacementAudioField.setEnabled(false);
        replacementAudioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replacementAudioFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Replacement audio");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14))
                    .addComponent(EnableSilenceReplaceChkBox)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(silenceBorderSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(slcBorderLbl))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(minSilenceLengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(silenceLengthLbl))
                    .addComponent(skipFirstCBox))
                .addGap(0, 58, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel7)
                    .addComponent(replacementAudioField, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(EnableSilenceReplaceChkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(silenceBorderSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slcBorderLbl))
                .addGap(2, 2, 2)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minSilenceLengthSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(silenceLengthLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(skipFirstCBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(replacementAudioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Silence replace", jPanel4);

        enableBgAudio.setText("Enable background audio");
        enableBgAudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableBgAudioActionPerformed(evt);
            }
        });

        bgAudioField.setEnabled(false);

        jLabel8.setText("Background audio file");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(enableBgAudio)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(bgAudioField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(enableBgAudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bgAudioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 286, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Background audio", jPanel6);

        EnableIntroChk.setText("Enable intro");
        EnableIntroChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnableIntroChkActionPerformed(evt);
            }
        });

        jLabel10.setText("Intro file");

        introField.setEnabled(false);
        introField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                introFieldActionPerformed(evt);
            }
        });

        cctIntroRBtn.setSelected(true);
        cctIntroRBtn.setText("Concatenate");
        cctIntroRBtn.setEnabled(false);
        cctIntroRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cctIntroRBtnActionPerformed(evt);
            }
        });

        StartNewsAtRBtn.setText("Start news at");
        StartNewsAtRBtn.setEnabled(false);
        StartNewsAtRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartNewsAtRBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("ms");

        startNewsMsSpin.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        startNewsMsSpin.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EnableIntroChk)
                    .addComponent(cctIntroRBtn)
                    .addComponent(StartNewsAtRBtn))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(startNewsMsSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addComponent(introField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(EnableIntroChk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(introField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cctIntroRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartNewsAtRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(startNewsMsSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Intro", jPanel3);

        enableOutroChkBox.setText("Enable outro");
        enableOutroChkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableOutroChkBoxActionPerformed(evt);
            }
        });

        jLabel13.setText("Outro file");

        OutroField.setEnabled(false);

        cctOutroRBtn.setSelected(true);
        cctOutroRBtn.setText("Concatenate");
        cctOutroRBtn.setEnabled(false);
        cctOutroRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cctOutroRBtnActionPerformed(evt);
            }
        });

        startOutroRBtn.setText("Start outro");
        startOutroRBtn.setEnabled(false);
        startOutroRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startOutroRBtnActionPerformed(evt);
            }
        });

        startOutroMsBefore.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        startOutroMsBefore.setEnabled(false);

        jLabel16.setText("ms before end");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enableOutroChkBox)
                    .addComponent(cctOutroRBtn)
                    .addComponent(startOutroRBtn))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(OutroField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(startOutroMsBefore, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(enableOutroChkBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OutroField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cctOutroRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startOutroRBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startOutroMsBefore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(0, 190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Outro", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startOutroRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startOutroRBtnActionPerformed
        cctOutroRBtn.setSelected(!startOutroRBtn.isSelected());
        selectFieldOutro();
    }//GEN-LAST:event_startOutroRBtnActionPerformed

    private void enableOutroChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableOutroChkBoxActionPerformed
        selectFieldOutro();
    }//GEN-LAST:event_enableOutroChkBoxActionPerformed

    private void StartNewsAtRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartNewsAtRBtnActionPerformed
        cctIntroRBtn.setSelected(!StartNewsAtRBtn.isSelected());
        selectFieldsIntro();
    }//GEN-LAST:event_StartNewsAtRBtnActionPerformed

    private void cctIntroRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cctIntroRBtnActionPerformed
        StartNewsAtRBtn.setSelected(!cctIntroRBtn.isSelected());
        selectFieldsIntro();
    }//GEN-LAST:event_cctIntroRBtnActionPerformed

    private void introFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_introFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_introFieldActionPerformed

    private void EnableIntroChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnableIntroChkActionPerformed
        selectFieldsIntro();
    }//GEN-LAST:event_EnableIntroChkActionPerformed

    private void enableBgAudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableBgAudioActionPerformed
        selectFieldsAudioBg();
    }//GEN-LAST:event_enableBgAudioActionPerformed

    private void replacementAudioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replacementAudioFieldActionPerformed

    }//GEN-LAST:event_replacementAudioFieldActionPerformed

    private void EnableSilenceReplaceChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnableSilenceReplaceChkBoxActionPerformed
        selectFieldsSlcReplace();
    }//GEN-LAST:event_EnableSilenceReplaceChkBoxActionPerformed

    private void minSilenceLengthSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_minSilenceLengthSliderStateChanged
        silenceLengthLbl.setText((float)minSilenceLengthSlider.getValue() / 100 + "");        // TODO add your handling code here:
    }//GEN-LAST:event_minSilenceLengthSliderStateChanged

    private void silenceBorderSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_silenceBorderSliderStateChanged
        if(silenceBorderSlider.getValue() > 0)
        {
            this.slcBorderLbl.setText("-" + silenceBorderSlider.getValue());
        }
        else
        {
            this.slcBorderLbl.setText("" + silenceBorderSlider.getValue());
        }
    }//GEN-LAST:event_silenceBorderSliderStateChanged

    private void rptChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptChkBoxActionPerformed
        HourCBox.setEnabled(!rptChkBox.isSelected());
    }//GEN-LAST:event_rptChkBoxActionPerformed

    private void WedChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WedChkBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WedChkBoxActionPerformed

    private void SrcFileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrcFileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SrcFileFieldActionPerformed

    private void SrcFileRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SrcFileRBtnActionPerformed
        DownloadRBtn.setSelected(!SrcFileRBtn.isSelected());
        SrcFileRBtn.setSelected(!DownloadRBtn.isSelected());
        selectFieldsGeneral();
    }//GEN-LAST:event_SrcFileRBtnActionPerformed

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void AuthChkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthChkBoxActionPerformed
        selectFieldsGeneral();
    }//GEN-LAST:event_AuthChkBoxActionPerformed

    private void UrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UrlFieldActionPerformed

    private void DownloadRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownloadRBtnActionPerformed
        SrcFileRBtn.setSelected(!DownloadRBtn.isSelected());
        DownloadRBtn.setSelected(!SrcFileRBtn.isSelected());
        selectFieldsGeneral();
    }//GEN-LAST:event_DownloadRBtnActionPerformed

    private void HourCBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HourCBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HourCBoxActionPerformed

    private void cctOutroRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cctOutroRBtnActionPerformed
        startOutroRBtn.setSelected(!cctOutroRBtn.isSelected());
        selectFieldOutro();        
    }//GEN-LAST:event_cctOutroRBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        Order order = new Order();
        
        setGeneral(order);
        
       if(EnableSilenceReplaceChkBox.isSelected())
       {
           setSlcReplace(order);
       }
       
       if(enableBgAudio.isSelected())
       {
           setBgAudio(order);
       }
       
       if(EnableIntroChk.isSelected())
       {
           setIntro(order);
       }
       
       if(enableOutroChkBox.isSelected())
       {
           setOutro(order);
       }
       
       this.dispose();
    }//GEN-LAST:event_saveBtnActionPerformed

    void setOutro(Order order)
    {
        if(cctOutroRBtn.isSelected())
        {
            Concat cct = new Concat();
            cct.setInput1(order.getInput());
            cct.setInput2(OutroField.getText());
            cct.setOutput("new" + order.getInput());
            
            order.setAction(cct);
        }
        
        if(startOutroRBtn.isSelected())
        {
            /*
            Mix m = new Mix();
            m.setInputs(OutroField.getText());
            m.setDelays(0);
            m.setInputs(order.getInput());
            m.setDelays((Integer)startNewsMsSpin.getValue());
            m.setDuration("longest");
            m.setOutput("new" + order.getInput());
            
            order.setAction(m);
            */
        }
        
        ShellCmd sh = new ShellCmd();
        sh.setCmd("rm -rf " + order.getInput());
        order.setAction(sh);

        sh.setCmd("mv " + "new" + order.getInput() + " " + order.getInput());
        order.setAction(sh);
    }
    
    void setIntro(Order order)
    {
        if(cctIntroRBtn.isSelected())
        {
            Concat cct = new Concat();
            cct.setInput1(order.getInput());
            cct.setInput2(introField.getText());
            cct.setOutput("new" + order.getInput());
            
            order.setAction(cct);
        }
        
        if(StartNewsAtRBtn.isSelected())
        {
            Mix m = new Mix();
            m.setInputs(introField.getText());
            m.setDelays(0);
            m.setInputs(order.getInput());
            m.setDelays((Integer)startNewsMsSpin.getValue());
            m.setDuration("longest");
            m.setOutput("new" + order.getInput());
            
            order.setAction(m);
        }
        
        ShellCmd sh = new ShellCmd();
        sh.setCmd("rm -rf " + order.getInput());
        order.setAction(sh);

        sh.setCmd("mv " + "new" + order.getInput() + " " + order.getInput());
        order.setAction(sh);
    }
    
    void setBgAudio(Order order)
    {
        Mix m = new Mix();
        m.setInputs(order.getInput());
        m.setDelays(0);
        m.setInputs(bgAudioField.getText());
        m.setDelays(0);       
        m.setDuration("first");
        m.setOutput("new" + order.getInput());
        
        order.setAction(m);
        
        ShellCmd sh = new ShellCmd();
        sh.setCmd("rm -rf " + order.getInput());
        order.setAction(sh);
        
        sh.setCmd("mv " + "new" + order.getInput() + " " + order.getInput());
        order.setAction(sh);
    }
    
    void setSlcReplace(Order order)
    {
        SilenceReplace slc = new SilenceReplace();
        slc.setSilenceBorder(silenceBorderSlider.getValue() *-1);   
        slc.setMinSilenceLength(minSilenceLengthSlider.getValue());
        slc.setInput(order.getInput());
        slc.setSkipFirst(skipFirstCBox.isSelected());
        slc.setReplacementAudioFile(replacementAudioField.getText());
        
        order.setAction(slc);
    }
    
    void setGeneral(Order order)
    {
        if(rptChkBox.isSelected())
        {
            order.setRepeat(true);
        }
        else
        {
            order.setHour(Integer.parseInt(this.HourCBox.getSelectedItem().toString()));
        }
        
        order.setMin(Integer.parseInt(this.MinCBox.getSelectedItem().toString()));
        order.setSec(Integer.parseInt(this.SecCBox.getSelectedItem().toString()));
        
        boolean days[] = {
            monChkBox.isSelected(), 
            TueChkBox.isSelected(), 
            WedChkBox.isSelected(), 
            ThuChkBox.isSelected(), 
            FriChkBox.isSelected(), 
            SatChkBox.isSelected(), 
            SunChkBox.isSelected() };
        
        int i = 0;
        order.setDays(0);
        for(boolean d : days)
        {
            order.setDays(order.getDays() | (d ? 1 : 0) << i++);
        }

        order.setOutput(OutroField.getText());
        
        if(DownloadRBtn.isSelected())
        {
            Download d = new Download();
            d.setUrl(UrlField.getText());
            d.setOutput("news.wav");
            
            if(AuthChkBox.isSelected())
            {
                d.setAuth(true);
                d.setUser(UserField.getText());
                d.setPass(PassField.getText());
            }
            order.setInput("news.wav");
            order.setAction(d);
        }
        
        if(SrcFileRBtn.isSelected())
        {
            order.setInput(SrcFileField.getText());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AuthChkBox;
    private javax.swing.JRadioButton DownloadRBtn;
    private javax.swing.JCheckBox EnableIntroChk;
    private javax.swing.JCheckBox EnableSilenceReplaceChkBox;
    private javax.swing.JCheckBox FriChkBox;
    private javax.swing.JTextField GeneralOutputField;
    private javax.swing.JComboBox<String> HourCBox;
    private javax.swing.JComboBox<String> MinCBox;
    private javax.swing.JTextField OutroField;
    private javax.swing.JTextField PassField;
    private javax.swing.JCheckBox SatChkBox;
    private javax.swing.JComboBox<String> SecCBox;
    private javax.swing.JTextField SrcFileField;
    private javax.swing.JRadioButton SrcFileRBtn;
    private javax.swing.JRadioButton StartNewsAtRBtn;
    private javax.swing.JCheckBox SunChkBox;
    private javax.swing.JCheckBox ThuChkBox;
    private javax.swing.JCheckBox TueChkBox;
    private javax.swing.JTextField UrlField;
    private javax.swing.JTextField UserField;
    private javax.swing.JCheckBox WedChkBox;
    private javax.swing.JTextField bgAudioField;
    private javax.swing.JRadioButton cctIntroRBtn;
    private javax.swing.JRadioButton cctOutroRBtn;
    private javax.swing.JCheckBox enableBgAudio;
    private javax.swing.JCheckBox enableOutroChkBox;
    private javax.swing.JTextField introField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSlider minSilenceLengthSlider;
    private javax.swing.JCheckBox monChkBox;
    private javax.swing.JTextField replacementAudioField;
    private javax.swing.JCheckBox rptChkBox;
    private javax.swing.JButton saveBtn;
    private javax.swing.JSlider silenceBorderSlider;
    private javax.swing.JLabel silenceLengthLbl;
    private javax.swing.JCheckBox skipFirstCBox;
    private javax.swing.JLabel slcBorderLbl;
    private javax.swing.JSpinner startNewsMsSpin;
    private javax.swing.JSpinner startOutroMsBefore;
    private javax.swing.JRadioButton startOutroRBtn;
    // End of variables declaration//GEN-END:variables

    void selectFieldOutro()
    {
        cctOutroRBtn.setEnabled(enableOutroChkBox.isSelected());
        OutroField.setEnabled(enableOutroChkBox.isSelected());
        startOutroRBtn.setEnabled(enableOutroChkBox.isSelected());  
        
        if(startOutroRBtn.isSelected())
        {
            startOutroMsBefore.setEnabled(enableOutroChkBox.isSelected());
        }
        else
        {
            startOutroMsBefore.setEnabled(false);
        }
    }
    
    void selectFieldsAudioBg()
    {
        bgAudioField.setEnabled(enableBgAudio.isSelected());
    }
    
    void selectFieldsSlcReplace()
    {
        silenceBorderSlider.setEnabled(EnableSilenceReplaceChkBox.isSelected());
        minSilenceLengthSlider.setEnabled(EnableSilenceReplaceChkBox.isSelected());
        skipFirstCBox.setEnabled(EnableSilenceReplaceChkBox.isSelected());
        replacementAudioField.setEnabled(EnableSilenceReplaceChkBox.isSelected());
    }
    
    void selectFieldsIntro()
    {
        if(EnableIntroChk.isSelected())
        {
            introField.setEnabled(true);
            StartNewsAtRBtn.setEnabled(true);
            cctIntroRBtn.setEnabled(true);
            if(StartNewsAtRBtn.isSelected())
            {
                startNewsMsSpin.setEnabled(true);
            }
            else
            {
                startNewsMsSpin.setEnabled(false);
            }
        }
        else
        {
            introField.setEnabled(false);
            startNewsMsSpin.setEnabled(false);
            StartNewsAtRBtn.setEnabled(false);
            cctIntroRBtn.setEnabled(false);
        }  
    }
    
    void selectFieldsGeneral()
    {
        UrlField.setEnabled(DownloadRBtn.isSelected());
        SrcFileField.setEnabled(SrcFileRBtn.isSelected());
        
        if(AuthChkBox.isSelected() && DownloadRBtn.isSelected())
        {
            UserField.setEnabled(DownloadRBtn.isSelected());
            PassField.setEnabled(DownloadRBtn.isSelected());         
        }
        else
        {
            UserField.setEnabled(false);
            PassField.setEnabled(false);
        }
        
    }
    
    
}

