/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jammnews;

import jammnews.dialogs.*;
import jammnews.tasks.*;
import java.awt.Color;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.tree.TreeModel;

/**
 *
 * @author dhergaarden
 */
public class JAMMNewsUI<T> extends javax.swing.JFrame {

    /**
     * Creates new form JAMMNewsUI
     */
    tcpConnection conn;
    JsonParser jp;
    private LinkedList<Task> tasks = new LinkedList<>();
    private int taskCount = 0;
    
    public JAMMNewsUI() {
        initComponents();
        actionsList.select(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        createConfig = new javax.swing.JButton();
        hourCbox = new java.awt.Choice();
        label1 = new java.awt.Label();
        actionsList = new java.awt.List();
        minCbox = new java.awt.Choice();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        rptChk = new java.awt.Checkbox();
        label5 = new java.awt.Label();
        addTask = new java.awt.Button();
        delTask = new java.awt.Button();
        taskList = new java.awt.List();
        label6 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        secCbox = new java.awt.Choice();
        editTask = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        remTaskList = new java.awt.List();
        label7 = new java.awt.Label();
        recTasksBtn = new javax.swing.JButton();
        rnowBtn = new javax.swing.JButton();
        connButton = new javax.swing.JButton();
        hostField = new javax.swing.JTextField();
        portField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        statLabel = new javax.swing.JLabel();
        disConnBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusTextArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createConfig.setText("Create Config");
        createConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createConfigActionPerformed(evt);
            }
        });

        for(int i = 0; i < 24; i++)
        {
            if(i < 10)
            hourCbox.add("0" + i + "");
            else
            hourCbox.add(i + "");
        }

        label1.setText("Action");

        actionsList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionsListActionPerformed(evt);
            }
        });

        for(int i = 0; i < 60; i++)
        {
            if(i < 10)
            minCbox.add("0" + i + "");
            else
            minCbox.add(i + "");
        }

        label2.setText("Time");

        label3.setText("Hour");

        label4.setText("Min");

        rptChk.setLabel("enable");

        label5.setText("Repeat hourly");

        addTask.setLabel("Add Task");
        addTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTaskActionPerformed(evt);
            }
        });

        delTask.setLabel("Del Task");
        delTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delTaskActionPerformed(evt);
            }
        });

        taskList.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                taskListItemStateChanged(evt);
            }
        });

        label6.setText("Task list");

        jLabel1.setText("Sec");

        for(int i = 0; i < 60; i+=10)
        {
            if(i < 10)
            secCbox.add("0" + i + "");
            else
            secCbox.add(i + "");
        }

        editTask.setLabel("Edit Task");
        editTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionsList, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(createConfig))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(hourCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(minCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(secCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rptChk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(addTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(delTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taskList, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(actionsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createConfig)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hourCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(minCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(secCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rptChk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(taskList, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );

        createConfig.getAccessibleContext().setAccessibleName("createConfig");
        actionsList.add("Download");
        actionsList.add("Mix");
        actionsList.add("Concatenate");
        actionsList.add("Shell Command");
        actionsList.add("Split Audio");
        actionsList.getAccessibleContext().setAccessibleName("");
        label2.getAccessibleContext().setAccessibleDescription("");
        addTask.getAccessibleContext().setAccessibleName("addTask");
        delTask.getAccessibleContext().setAccessibleName("delTask");
        taskList.getAccessibleContext().setAccessibleName("taskList");

        jTabbedPane5.addTab("Schedular", jPanel1);
        jPanel1.getAccessibleContext().setAccessibleName("schedular");

        label7.setText("Task list");

        recTasksBtn.setText("Receive Tasks");
        recTasksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recTasksBtnActionPerformed(evt);
            }
        });

        rnowBtn.setText("Run now");
        rnowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnowBtnActionPerformed(evt);
            }
        });

        connButton.setText("Connect");
        connButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connButtonActionPerformed(evt);
            }
        });

        hostField.setText("localhost");

        portField.setText("4444");

        jLabel2.setText("Host");

        jLabel3.setText("Port");

        statLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 120)); // NOI18N
        statLabel.setForeground(new java.awt.Color(255, 0, 0));
        statLabel.setText(".");
        statLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        disConnBtn.setText("Disconnect");
        disConnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disConnBtnActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        statusTextArea.setColumns(20);
        statusTextArea.setRows(5);
        statusTextArea.setEnabled(false);
        jScrollPane2.setViewportView(statusTextArea);

        jLabel5.setText("Status");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(recTasksBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rnowBtn)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(remTaskList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(connButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(disConnBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 276, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connButton)
                    .addComponent(disConnBtn)
                    .addComponent(statLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recTasksBtn)
                    .addComponent(rnowBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(remTaskList, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane5.addTab("Remote", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTaskActionPerformed

        Task t = tasks.get(taskList.getSelectedIndex());

        if(Download.class.isInstance(t.getAction()))
        {
            DownloadDialog dd = new DownloadDialog(this, (Download)t.getAction(), taskList.getSelectedIndex());
            dd.setAlwaysOnTop(true);
            dd.setVisible(true);
        }

        if(Mix.class.isInstance(t.getAction()))
        {
            MixDialog md = new MixDialog(this,(Mix)t.getAction(), taskList.getSelectedIndex());
            md.setAlwaysOnTop(true);
            md.setVisible(true);
        }

        if(Concat.class.isInstance(t.getAction()))
        {
            ConcatDialog cd = new ConcatDialog(this, (Concat)t.getAction(), taskList.getSelectedIndex());
            cd.setAlwaysOnTop(true);
            cd.setVisible(true);
        }

        if(ShellCmd.class.isInstance(t.getAction()))
        {
            ShellCmdDialog scd = new ShellCmdDialog(this, (ShellCmd)t.getAction(), taskList.getSelectedIndex() );
            scd.setAlwaysOnTop(true);
            scd.setVisible(true);
        }
        
        if(Split.class.isInstance(t.getAction()))
        {
            SplitDialog spd = new SplitDialog(this, (Split)t.getAction(), taskList.getSelectedIndex());
            spd.setAlwaysOnTop(true);
            spd.setVisible(true);
        }
    }//GEN-LAST:event_editTaskActionPerformed

    private void taskListItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_taskListItemStateChanged
        hourCbox.select(tasks.get(taskList.getSelectedIndex()).getHour());
        minCbox.select(tasks.get(taskList.getSelectedIndex()).getMin());
        secCbox.select(tasks.get(taskList.getSelectedIndex()).getSec() / 10);
        rptChk.setState(tasks.get(taskList.getSelectedIndex()).isRepeat());
    }//GEN-LAST:event_taskListItemStateChanged

    private void delTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delTaskActionPerformed
        tasks.remove(taskList.getSelectedIndex());
        refreshList();
    }//GEN-LAST:event_delTaskActionPerformed

    private void addTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTaskActionPerformed
        String selected = actionsList.getSelectedItem();

        if(selected == "Download")
        {
            DownloadDialog dd = new DownloadDialog(this);
            dd.setAlwaysOnTop(true);
            dd.setVisible(true);
        }

        if(selected == "Mix")
        {
            MixDialog md = new MixDialog(this);
            md.setAlwaysOnTop(true);
            md.setVisible(true);
        }

        if(selected == "Concatenate")
        {
            ConcatDialog cd = new ConcatDialog(this);
            cd.setAlwaysOnTop(true);
            cd.setVisible(true);
        }

        if(selected == "Shell Command")
        {
            ShellCmdDialog scd = new ShellCmdDialog(this);
            scd.setAlwaysOnTop(true);
            scd.setVisible(true);
        }
        
        if(selected == "Split Audio")
        {
            SplitDialog spd = new SplitDialog(this);
            spd.setAlwaysOnTop(true);
            spd.setVisible(true);
        }
    }//GEN-LAST:event_addTaskActionPerformed

    private void actionsListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionsListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionsListActionPerformed

    private void createConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createConfigActionPerformed
        jp = new JsonParser(tasks);
        JFileChooser fileChooser = new JFileChooser();

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        {
            File file = fileChooser.getSelectedFile();
            BufferedWriter writer;
            try {
                writer = new BufferedWriter(new FileWriter(file.getAbsolutePath()));
                writer.write(jp.getJson(),0,jp.getJson().length());
                writer.close();
            } catch (IOException ex) {
                Logger.getLogger(JAMMNewsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_createConfigActionPerformed

    private void connButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connButtonActionPerformed
        conn = new tcpConnection(hostField.getText(), 4444);
        if(conn.getConnectionState())
        {
            statLabel.setForeground(Color.green);
        }
    }//GEN-LAST:event_connButtonActionPerformed

    private void recTasksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recTasksBtnActionPerformed
        if(conn.getConnectionState())
        {
            conn.writeToConnection("getConf");
            try {
                sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(JAMMNewsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            while(conn.dataAvailable())
            {
                conn.readFromConnection();
            } 
            jp = new JsonParser(conn.getReceived());
            tasks = jp.getTaskList();
            refreshList();
        }
    }//GEN-LAST:event_recTasksBtnActionPerformed

    private void rnowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnowBtnActionPerformed
        if(conn.getConnectionState())
        {
            if(!(remTaskList.getSelectedIndex() < 0))
            {
                statusTextArea.setText("");
                conn.writeToConnection("runnow(" + remTaskList.getSelectedIndex() + ")");
                            try {
                sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(JAMMNewsUI.class.getName()).log(Level.SEVERE, null, ex);
            }
                while(conn.dataAvailable())
                {
                    conn.readFromConnection();
                    statusTextArea.setText(statusTextArea.getText() + "\n" + conn.getReceived());
                }
            }
        }
    }//GEN-LAST:event_rnowBtnActionPerformed

    private void disConnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disConnBtnActionPerformed
        if(conn.disConnect())
        {
            statLabel.setForeground(Color.red);
        }
    }//GEN-LAST:event_disConnBtnActionPerformed

    public <T> void addTaskHandler(T ac)
    {        
        Task t = new Task();           
        t.setAction(ac);
        t.setRepeat(rptChk.getState());
        t.setHour(Integer.parseInt(hourCbox.getSelectedItem()));
        t.setMin(Integer.parseInt(minCbox.getSelectedItem()));
        t.setSec(Integer.parseInt(secCbox.getSelectedItem()));
        
        tasks.addLast(t);
        refreshList();
    }
    
    public <T> void editTaskHandler(T ac, int index)
    {        
        Task t = new Task();           
        t.setAction(ac);
        t.setRepeat(rptChk.getState());
        t.setHour(Integer.parseInt(hourCbox.getSelectedItem()));
        t.setMin(Integer.parseInt(minCbox.getSelectedItem()));
        t.setSec(Integer.parseInt(secCbox.getSelectedItem()));
        
        tasks.set(index, t);
        refreshList();
    }
    
    private void refreshList()
    {
        //taskList.removeAll();
        remTaskList.removeAll();
        String action = "";
    
        for (Task t : tasks) 
        {
            if(Download.class.isInstance(t.getAction()))
            {
                action = "download";
            }

            if(Mix.class.isInstance(t.getAction()))
            {
                action = "mix";
            }

            if(Concat.class.isInstance(t.getAction()))
            {
                action = "cct";
            }

            if(ShellCmd.class.isInstance(t.getAction()))
            {
                action = "cmd";
            }
            
            if(Split.class.isInstance(t.getAction()))
            {
                action = "Split";
            }
        
            String taskStr = "\t Action : " +
            action + 
            "\t Time : " + 
            makeTime(t.getHour()) +
            ":" +
            makeTime(t.getMin()) +
            ":" +
            makeTime(t.getSec()) + 
            "\t Repeat : " + 
            t.isRepeat();
            
            remTaskList.add(taskStr);
            taskList.add(taskStr);            
        }
    }
    
    private String makeTime(int t)
    {
        if(t < 10)
            return "0" + t;
        else
            return t + "";
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JAMMNewsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JAMMNewsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JAMMNewsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JAMMNewsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JAMMNewsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List actionsList;
    private java.awt.Button addTask;
    private javax.swing.JButton connButton;
    private javax.swing.JButton createConfig;
    private java.awt.Button delTask;
    private javax.swing.JButton disConnBtn;
    private java.awt.Button editTask;
    private javax.swing.JTextField hostField;
    private java.awt.Choice hourCbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Choice minCbox;
    private javax.swing.JTextField portField;
    private javax.swing.JButton recTasksBtn;
    private java.awt.List remTaskList;
    private javax.swing.JButton rnowBtn;
    private java.awt.Checkbox rptChk;
    private java.awt.Choice secCbox;
    private javax.swing.JLabel statLabel;
    private javax.swing.JTextArea statusTextArea;
    private java.awt.List taskList;
    // End of variables declaration//GEN-END:variables
}
